# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [1]:
#type your code here
import numpy as np

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [2]:
#type your code here
cupcakes=np.array([2,0.75,2,1,0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [33]:
recipes=np.loadtxt(open('recipes.csv','r'),delimiter=',')
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [38]:
#type your code here
print('Cupcakes:',recipes[0,:])
print('Pancakes:',recipes[1,:])
print('Cookie:',recipes[2,:])
print('Bread:',recipes[3,:])

Cupcakes: [2.   0.75 2.   1.   0.5 ]
Pancakes: [1.    0.125 1.    1.    0.125]
Cookie: [2.75 1.5  1.   0.   1.  ]
Bread: [4.  0.5 2.  2.  0.5]


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [39]:
#type your code here
eggs = recipes[:,3]
eggs

array([1., 1., 0., 2.])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [41]:
#type your code here
mask = (eggs == 1)
print(mask)
print('Pancake:-',recipes[mask][0])
print('Cookie:-',recipes[mask][1])
recipes[mask]

[ True  True False False]
Pancake:- [2.   0.75 2.   1.   0.5 ]
Cookie:- [1.    0.125 1.    1.    0.125]


array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125]])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [42]:
#type your code here
cookies = recipes[2,:]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [43]:
#type your code here
double_batch = cupcakes*2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [44]:
#type your code here
grocery_list = cookies+double_batch
grocery_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])